services:
  shop-api:
    platform: linux/amd64
    image: cosmtrek/air:v1.61.0
    container_name: shop-api
    working_dir: /go/src/github.com/tamaco489/elasticsearch_demo/api/shop
    volumes:
      - ./shop:/go/src/github.com/tamaco489/elasticsearch_demo/api/shop
      - ~/.cache/go-build:/root/.cache/go-build
    ports:
      - "8080:8080"
    networks:
      - sandbox

  opensearch:
    image: opensearchproject/opensearch:2.19.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch # Name the node that will run in this container
      - discovery.seed_hosts=opensearch # Only the current node is needed for discovery
      - discovery.type=single-node # シングルノードモードに設定
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - ./shop/docker/opensearch/node1/data:/usr/share/opensearch/data # Mount host directory to container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - sandbox

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]' # Only opensearch is available
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # Disables security dashboards plugin in OpenSearch Dashboards
    networks:
      - sandbox

networks:
  sandbox:
